[app]
name = "create-express-app"
version = 1

[server]
addr = "127.0.0.1"
port = 8008
limit = "20mb"
prefix = "api"

[jwt]
secret = "Rfe5lNnO4n3MIEJG"
expireHour = 120

[db]
url = "file:sqlite.db"
# https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/error-formatting
errorFormat = "minimal"
